### ISSUE TITLE
Feedback entrega 1

### ISSUE THREAD

**Issue by edjus** [enzoponf3/AlgoOfEmpires#2]
@ConstanzaFrutos @sebapenna @NicoGarofalo @enzoponf3 
Algunas observaciones y cosas a corregir respecto a la primera entrega.

- [x] Por convención todas las interfaces empiezan con el prefijo I: ```IEstadoAldeano```. Hacer un refactor.

- [x] ```Objeto -> IEntidad, UnidadMovible -> IMovible```, ya que por como está ahora aparenta que ```UnidadMovible``` sería un especialización de ``Unidad```: ```UnidadMovible extendens Unidad``` que no es lo que se quiere.
- [x] Reemplazar iteradores por foreach, hace más legible el código.
- [x] No crear métodos que solo se usen para las pruebas: interfaz EstadoCasillero, método estaOcupado no debería existir. Alcanza con probar a travéz de funcionalidades en este caso lanzar excepcion.
- [x] El mensaje ```estaOcupado()``` de la clase Casillero no es necesario que llame al ```EstadoDelCasillero``` si el tiene el objeto (ocupante) solo debe verificar que este exista. Si queremos ser más exactos se debería fijarse que el que está en esa posición es el que ubicamos. ```esOcupadoPor(Objeto)```.
- [x] Al remover un Objeto de un casillero se debería setear el ocupante del casillero (uso justificado de un setter) y no usar un atributo protegido. Todos los atributos deben ser privados y protegidos si hay herencia y queremos que la clase hija lo tenga. El usarlos fuera de este contexto es una **violación al encapsulamiento.**
- [x] No atrapar una excepción si solo la vamos a lanzar de nuevo, éste se propaga automáticamente.
- [x] Falta probar 2 excepciones: ```AldeanoNoAtacaException``` y ```UnidadFueraDeRangoException```.
- [x] Faltan probar métodos por ejemplo: esIgualA() de la clase casillero, recuerdan que se trata de usar la metodología de TDD por lo que debe haber mínimo una prueba por método.
- [x] Si deciden que un objeto se tiene que crear con cierto estado base, es decir que no tenga sentido la existencia del objeto sin ese atributo, por ejemplo que un aldeano se crea en una posición, al crearlo se le debe pasar por constructor su posición y no después de crearlo.
Esto se usa generalmente en las asociaciones de tipo composición, al crear un objeto se debe asegurar que el mismo se cree en un estado válido dentro del contexto del modelo.
- [x] El método reparar de la clase abstracta Edificio no se llega a ejecutar, se redefine en todas las clases hijas, marcarlo como un método abstracto. Fíjense que no les pase lo mismo con otras clases abstractas.
- [x] No es correcto usar atributos protegidos para modificar la vida en la reparación de edificios (se usan como si fueran públicos) estan **violando el encapsulamiento**. Se debe generar una secuencia de mensajes que garanticen la no violación de éste.
- [x] Si el estado de un edificio es en construcción no debería preguntar por la cantidad de turnos debería lanzar la excepción.
- [x] En los test de creación verificar que después de la creación el objeto devuelto existe no solo esperar que no lance la excepción.
- [x] Se debe probar las funcionalidades que duren más de un turno, ejemplo: construcción de cuartel, se debe verificar que no puede crear un arquero durante los turnos que todavia se está creando, lanzando la excepción correspondiente.
- [x] Reorganizar paquetes no tener todas las clases en un solo paquete acomodarlas como mejor les parezca.
- [x] Eliminar aquellos branch que no se usen o estén repetidos. Tratar de mejorar el uso de los mismos generando branchs por funcionalidad tal vez por ser un proyecto pequeño esto no es posible, pero debería poder separarse en módulos: sistema de juego y turnos, unidades (movimiento y ataque), implementación de la parte gráfica (Java FX) esto debe ser posible ya que se programa contra interfaces y no contra implementaciones inclusive si son más genéricos se podría generar un sistema de movimiento y sistema de ataque. Si fallan en esto quiere decir que su solución tiene un alto acoplamiento lo cual se debe evitar.
- [x] Corregir el diagrama de estado, todo lo que se pueda destruir termina en un estado de muerto o destruido.

- Tratar de actualizar regularmente la rama principal. 

Sobre este supuesto no lo llego a entender del todo.
Al concluir un turno se debe volver al estado original de los edificios, es decir, previo a que sellevara a cabo el mismo. De esta manera, por ejemplo. en el próximo turno se podrá volver a reparar un edificio o continuar su construcción.
No sería correcto que un edificio que esté siendo reparado vuelva al estado original debería continuar siendo reparado.

**Comment by edjus** [comment]
Cualquier duda que tengan no duden en mandarme un mail. 
Por ahí quedó algo desactualizado algunos puntos ya que estuvieron commiteando mientras revisaba.
Hice un cambio en las observaciones, para que marquen según las van viendo, facilita la corrección.

**Comment by ConstanzaFrutos** [comment]
Hola Edson, en tanto a la interfaz IUnidadMovible, ¿esta mal que esta herede de IEntidad? En nuestro problema nunca vamos a agregar cosas que no sean una entidad, y si no hereda de esta tenemos problemas de tipos. Hay casos en los que necesitamos guardar una UnidadMovible para asegurarnos de que no vamos a meter por ej un edificio, que claramente no se puede mover, para estos casos es util, pero tiene que heredar de IEntidad para que lo reconozca luego como una entidad.

En tanto a la corrección de remover en el casillero, no entiendo que tenemos que setear. Porque el casillero debería quedar con objeto apuntando a Null, lo que indica que no tiene nada.

**Comment by edjus** [comment]
Hola, sobre el casillero es correcto como lo están haciendo, antes me parece que se usaba un método protegido: ```casillero.entidad = null``` o algo así. Revisando lo último se me hace raro que exista dos mensajes: ```removerObjeto()``` y ```desocupar()```, incluso esto mismo se puede mejorar a la hora de agregar un objeto, pueden hacer por ejemplo: ```this.estado = this.estado.removerObjeto()``` de esta manera al remover un objeto también se setea el cambio de estado por lo que en vez de devolver void tanto remover como ocupar, podrian devolver ```IEstadoCasillero```.

Sobre el tema de interfaz IUnidadMovible, no está mal que una interfaz extienda de otra, si les parece correcto háganlo sin ningún problema, tengan en cuenta otras posibilidades que la clase implemente ambas interfaces ```public class A implements C,D {...}``` de esta manera de acuerdo a como sean los parámetros en los métodos se va a comportar como C o D.

**Comment by ConstanzaFrutos** [comment]
¡Muchas gracias! 

Unidad implementa ambas, IEntidad Y IUnidadMovible, el problema es cuando guardamos IEntidades y queremos sacar IUnidadMovibles, ahi es cuando necesitamos que IUnidadMovibles extienda IEntidad.
